<?php

namespace PutYourZikBundle\Repository;

/**
 * MusicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMusicByPlaylist($id)
    {
        $qb = $this->createQueryBuilder('m')
            ->select('m')
            ->where('m.playlist = :id')
            ->setParameter(':id', $id)
            ->getQuery();

        return $qb->getResult();
    }
}
