<?php

namespace PutYourZikBundle\Repository;

/**
 * PlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistRepository extends \Doctrine\ORM\EntityRepository {

    public function findPlaylistByUser($id)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.user = :id')
            ->setParameter(':id', $id)
            ->getQuery();

        return $qb->getResult();
    }
}
