<?php

namespace PutYourZikBundle\Repository;



/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findToken($mail, $token) {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.email = :mail')
            ->andWhere('u.token = :token')
            ->setParameter('mail', $mail)
            ->setParameter('token', $token)
            ->getQuery();

        return $qb->getResult();
    }
}
