put_your_zik_publication:
    resource: "@PutYourZikBundle/Resources/config/routing/publication.yml"
    prefix:   /publication

put_your_zik_homepage:
    path:     /
    defaults: { _controller: PutYourZikBundle:Request:request }

put_your_zik_test:
    path:    /test
    defaults: { _controller: PutYourZikBundle:Request:getInfos }

put_you_zik_profil:
    path:    /profil/{id}
    defaults: { _controller: PutYourZikBundle:Request:userPlaylists }
